### PR TITLE
Add support for TCP-based connections

### PR DESCRIPTION
**Pull request by kccqzy**
This PR adds support for TCP-based connections. No existing code is touched, so no existing APIs would break. It only adds a new module specific for creating TCP connections and sending events/queries over them.

### CODE REVIEW

**Comment by kccqzy** [comment]
The project can be built with the `stack` tool. Here is the `stack.yaml`:

``` yaml
# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.1

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- base-orphans-0.5.1
- errors-1.4.7
- text-1.2.2.0
- transformers-0.4.3.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```

But a more permanent solution might be to drop the `errors < 2.0` requirement.

**Comment by telser** [comment]
@kccqzy Thanks! I have no problems doing this, but really the upstream version should get released on hackage and use that instead. This looks to be the same as the one there, right? It would probably be best to get behind one and push it forward. The upstream has progressed since I forked back in June, and is better for the community to prefer that IMO. 

Also, for the errors requirement, I don't recall but there was some conflict in the past that drove that requirement. But I hadn't yet made the switch to stack, which solves many of those issues. So again, I don't want to dismiss the work you did here, but I view it as better to drop the divergent changes and use the upstream that @tel has.

**Comment by kccqzy** [comment]
@telser Thanks for the explanation. I originally used the upstream version but found that it wasn't on Hackage so I switched to yours (easier to use a version on Hackage). In this case it seems quite strange that a search for riemann on Hackage returns yours instead of the upstream's. But anyway I agree with what you have said; I'll find out a way to convince the upstream to release on Hackage.

**Comment by telser** [comment]
@kccqzy The upstream version is now on hackage at version 0.1.1! Agreed that it is much easier to use a hackage released version.

**Pull request closed without merging**
